### ISSUE TITLE
Avatar disappeared after reaching level 2

### ISSUE THREAD

**Issue by paulvt** [remjey/HabitSailor#1]
After being promoted to level 2, my avatar disappeared in HabitSailor.  I just see an empty square now.

**Comment by remjey** [comment]
The profile picture code is not very good atm, so there may be hiccups and the picture may be out of date, it depends on the server generating the picture and sometimes the server feels lazy.

This will be fixed later though, because the good method for displaying the profile picture is not trivial whereas the functionality itself is not very important.

Refreshing or restarting the app should reload the profile picture.

**Comment by paulvt** [comment]
Yes, I saw you wrote down that the avatar code needs to be better somewhere.
I just wanted to report it, so people will not keep filing issues about this.

Btw, restarting nor refreshing helps.

**Comment by remjey** [comment]
Ok this is weird, I’ll have a look at it.

If you have a few minutes, you can get your user ID in [this page](https://habitica.com/#/options/settings/api) and then try the following URL in your browser, after replacing `uuid` with your User ID: `https://habitica.com/export/avatar-uuid.png`. (eg: `https://habitica.com/export/avatar-abcd0123-1234-1234-5678-abcd01234567.png`)

Calling this URL generates a PNG picture of your avatar and redirects to its URL on AWS. If it fails, then it is a server problem, which could happen since this API call seems pretty much unused nowadays and could have become buggy over time.

**Comment by paulvt** [comment]
Ok, of course I start HabitSalor today and the avatar is back? I don't know what happened and cannot debug it now.  I'll reopen if it reoccurs with the information you asked for.
